imgData = [
   "images/big/almond_butter.png",
   "images/big/apple_fruit.png",
   "images/big/apricot.png",
   "images/big/artichoke.png",
   "images/big/asparagus.png",
   "images/big/avocado.png",
   "images/big/bacon.png",
   "images/big/baguette.png",
   "images/big/banana.png",
   "images/big/basil.png",
   "images/big/beet.png",
   "images/big/black_pepper.png",
   "images/big/black_sesame_seeds.png",
   "images/big/blueberry.png",
   "images/big/bok_choy.png",
   "images/big/brazil_nut.png",
   "images/big/bread_crumbs.png",
   "images/big/bread_loaf.png",
   "images/big/brezel.png",
   "images/big/broccoli.png",
   "images/big/broccolini.png",
   "images/big/butter.png",
   "images/big/cabbage.png",
   "images/big/carrot.png",
   "images/big/cashew.png",
   "images/big/cauliflower.png",
   "images/big/caviar.png",
   "images/big/celery.png",
   "images/big/chapati.png",
   "images/big/chard.png",
   "images/big/cheese.png",
   "images/big/chili_pepper.png",
   "images/big/cinnamon_sticks.png",
   "images/big/coconut.png",
   "images/big/coffee_beans.png",
   "images/big/collard_greens.png",
   "images/big/corn.png",
   "images/big/crab.png",
   "images/big/cucumber.png",
   "images/big/curry.png",
   "images/big/cutted_melon.png",
   "images/big/cutted_watermelon.png",
   "images/big/dairy.png",
   "images/big/date_fruit.png",
   "images/big/dressed_fish.png",
   "images/big/durian.png",
   "images/big/eggplant.png",
   "images/big/finocchio.png",
   "images/big/firm_tofu.png",
   "images/big/no_crustaceans.png",
   "images/big/no_eggs.png",
   "images/big/no_fish.png",
   "images/big/no_fructose.png",
   "images/big/no_gluten.png",
   "images/big/no_gmo.png",
   "images/big/no_lupines.png",
   "images/big/no_meat.png",
   "images/big/no_mustard.png",
   "images/big/no_nuts.png",
   "images/big/no_peanut.png",
   "images/big/no_pork.png",
   "images/big/no_sesame.png",
   "images/big/no_sugar.png",
   "images/big/non_lactose_food.png",
   "images/big/nut.png",
   "images/big/olive.png",
   "images/big/olive_oil.png",
   "images/big/onion.png",
   "images/big/orange.png",
   "images/big/papaya.png",
   "images/big/paprika.png",
   "images/big/peach.png",
   "images/big/peanut_butter.png",
   "images/big/peanuts.png",
   "images/big/pear.png",
   "images/big/peas.png",
   "images/big/pecan.png",
   "images/big/pineapple.png",
   "images/big/plum.png",
   "images/big/pomegranate.png",
   "images/big/potato.png",
   "images/big/prawn.png",
   "images/big/pretzel.png",
   "images/big/pumpkin.png",
   "images/big/rack_of_lamb.png",
   "images/big/radish.png",
   "images/big/raisins.png",
   "images/big/raspberry.png",
   "images/big/red_and_black_beans.png",
   "images/big/rice_vinegar.png",
   "images/big/rolled_oats.png",
   "images/big/salsa.png",
   "images/big/salt.png",
   "images/big/sausage.png",
   "images/big/sesame.png",
   "images/big/shrimp_and_lobster.png",
   "images/big/silken_tofu.png",
   "images/big/smoked_paprika.png",
   "images/big/soursop.png",
   "images/big/soy.png",
   "images/big/soy_sauce.png",
   "images/big/spinach.png",
   "images/big/squash.png",
   "images/big/steak.png",
   "images/big/sugar.png",
   "images/big/sugar_free.png",
   "images/big/sunny_side_up_eggs.png",
   "images/big/sweet_potato.png",
   "images/big/tangelo.png",
   "images/big/thanksgiving.png",
   "images/big/tomato.png",
   "images/big/turmeric.png",
   "images/big/vegetable_bouillion_paste.png",
   "images/big/vegetables_bag.png",
   "images/big/whipped_cream.png",
   "images/big/white_beans.png",
   "images/big/you_choy.png"
]


imgName= [
    "Almond butter",
    "Apple fruit",
    "Apricot",
    "Artichoke",
    "Asparagus",
    "Avocado",
    "Bacon",
    "Baguette",
    "Banana",
    "Basil",
    "Beet",
    "Black pepper",
    "Black sesame seeds",
    "Blueberry",
    "Bok choy",
    "Brazil nut",
    "Bread crumbs",
    "Bread loaf",
    "Brezel",
    "Broccoli",
    "Broccolini",
    "Butter",
    "Cabbage",
    "Carrot",
    "Cashew",
    "Cauliflower",
    "Caviar",
    "Celery",
    "Chapati",
    "Chard",
    "Cheese",
    "Chili pepper",
    "Cinnamon sticks",
    "Coconut",
    "Coffee beans",
    "Collard greens",
    "Corn",
    "Crab",
    "Cucumber",
    "Curry",
    "Cutted melon",
    "Cutted watermelon",
    "Dairy",
    "Date fruit",
    "Dressed fish",
    "Durian",
    "Eggplant",
    "Finocchio",
    "Firm tofu",
    "Non lactose food",
    "Nut",
    "Olive",
    "Olive oil",
    "Onion",
    "Orange",
    "Papaya",
    "Paprika",
    "Peach",
    "Peanut butter",
    "Peanuts",
    "Pear",
    "Peas",
    "Pecan",
    "Pineapple",
    "Plum",
    "Pomegranate",
    "Potato",
    "Prawn",
    "Pretzel",
    "Pumpkin",
    "Rack of lamb",
    "Radish",
    "Raisins",
    "Raspberry",
    "Red and black beans",
    "Rice vinegar",
    "Rolled oats",
    "Salsa",
    "Salt",
    "Sausage",
    "Sesame",
    "Shrimp and lobster",
    "Silken tofu",
    "Smoked paprika",
    "Soursop",
    "Soy",
    "Soy sauce",
    "Spinach",
    "Squash",
    "Steak",
    "Sugar",
    "Sugar free",
    "Sunny side up eggs",
    "Sweet potato",
    "Tangelo",
    "Thanksgiving",
    "Tomato",
    "Turmeric",
    "Vegetable bouillion paste",
    "Vegetables bag",
    "Whipped cream",
    "White beans",
    "You choy",
]