imgData = {
    "Almond butter": "images/big/almond_butter.png",
    "Apple fruit": "images/big/apple_fruit.png",
    "Apricot": "images/big/apricot.png",
    "Artichoke": "images/big/artichoke.png",
    "Asparagus": "images/big/asparagus.png",
    "Avocado": "images/big/avocado.png",
    "Bacon": "images/big/bacon.png",
    "Baguette": "images/big/baguette.png",
    "Banana": "images/big/banana.png",
    "Basil": "images/big/basil.png",
    "Beet": "images/big/beet.png",
    "Black pepper": "images/big/black_pepper.png",
    "Black sesame seeds": "images/big/black_sesame_seeds.png",
    "Blueberry": "images/big/blueberry.png",
    "Bok choy": "images/big/bok_choy.png",
    "Brazil nut": "images/big/brazil_nut.png",
    "Bread crumbs": "images/big/bread_crumbs.png",
    "Bread loaf": "images/big/bread_loaf.png",
    "Brezel": "images/big/brezel.png",
    "Broccoli": "images/big/broccoli.png",
    "Broccolini": "images/big/broccolini.png",
    "Butter": "images/big/butter.png",
    "Cabbage": "images/big/cabbage.png",
    "Carrot": "images/big/carrot.png",
    "Cashew": "images/big/cashew.png",
    "Cauliflower": "images/big/cauliflower.png",
    "Caviar": "images/big/caviar.png",
    "Celery": "images/big/celery.png",
    "Chapati": "images/big/chapati.png",
    "Chard": "images/big/chard.png",
    "Cheese": "images/big/cheese.png",
    "Chili pepper": "images/big/chili_pepper.png",
    "Cinnamon sticks": "images/big/cinnamon_sticks.png",
    "Coconut": "images/big/coconut.png",
    "Coffee beans": "images/big/coffee_beans.png",
    "Collard greens": "images/big/collard_greens.png",
    "Corn": "images/big/corn.png",
    "Crab": "images/big/crab.png",
    "Cucumber": "images/big/cucumber.png",
    "Curry": "images/big/curry.png",
    "Cutted melon": "images/big/cutted_melon.png",
    "Cutted watermelon": "images/big/cutted_watermelon.png",
    "Dairy": "images/big/dairy.png",
    "Date fruit": "images/big/date_fruit.png",
    "Dressed fish": "images/big/dressed_fish.png",
    "Durian": "images/big/durian.png",
    "Eggplant": "images/big/eggplant.png",
    "Finocchio": "images/big/finocchio.png",
    "Firm tofu": "images/big/firm_tofu.png",
    "Non lactose food": "images/big/non_lactose_food.png",
    "Nut": "images/big/nut.png",
    "Olive": "images/big/olive.png",
    "Olive oil": "images/big/olive_oil.png",
    "Onion": "images/big/onion.png",
    "Orange": "images/big/orange.png",
    "Papaya": "images/big/papaya.png",
    "Paprika": "images/big/paprika.png",
    "Peach": "images/big/peach.png",
    "Peanut butter": "images/big/peanut_butter.png",
    "Peanuts": "images/big/peanuts.png",
    "Pear": "images/big/pear.png",
    "Peas": "images/big/peas.png",
    "Pecan": "images/big/pecan.png",
    "Pineapple": "images/big/pineapple.png",
    "Plum": "images/big/plum.png",
    "Pomegranate": "images/big/pomegranate.png",
    "Potato": "images/big/potato.png",
    "Prawn": "images/big/prawn.png",
    "Pretzel": "images/big/pretzel.png",
    "Pumpkin": "images/big/pumpkin.png",
    "Rack of lamb": "images/big/rack_of_lamb.png",
    "Radish": "images/big/radish.png",
    "Raisins": "images/big/raisins.png",
    "Raspberry": "images/big/raspberry.png",
    "Red and black beans": "images/big/red_and_black_beans.png",
    "Rice vinegar": "images/big/rice_vinegar.png",
    "Rolled oats": "images/big/rolled_oats.png",
    "Salsa": "images/big/salsa.png",
    "Salt": "images/big/salt.png",
    "Sausage": "images/big/sausage.png",
    "Sesame": "images/big/sesame.png",
    "Shrimp and lobster": "images/big/shrimp_and_lobster.png",
    "Silken tofu": "images/big/silken_tofu.png",
    "Smoked paprika": "images/big/smoked_paprika.png",
    "Soursop": "images/big/soursop.png",
    "Soy": "images/big/soy.png",
    "Soy sauce": "images/big/soy_sauce.png",
    "Spinach": "images/big/spinach.png",
    "Squash": "images/big/squash.png",
    "Steak": "images/big/steak.png",
    "Sugar": "images/big/sugar.png",
    "Sugar free": "images/big/sugar_free.png",
    "Sunny side up eggs": "images/big/sunny_side_up_eggs.png",
    "Sweet potato": "images/big/sweet_potato.png",
    "Tangelo": "images/big/tangelo.png",
    "Thanksgiving": "images/big/thanksgiving.png",
    "Tomato": "images/big/tomato.png",
    "Turmeric": "images/big/turmeric.png",
    "Vegetable bouillion paste": "images/big/vegetable_bouillion_paste.png",
    "Vegetables bag": "images/big/vegetables_bag.png",
    "Whipped cream": "images/big/whipped_cream.png",
    "White beans": "images/big/white_beans.png",
    "You choy": "images/big/you_choy.png",
}